sudo: false
language: node_js

node_js:
  - "6"
  - "7"
  
services:
  - mongodb
  - redis-server

before_install:
  - 'npm install -g npm@latest'
  
install:
  - 'npm install'
  - 'sh ./patchesCheck.sh'
  - 'npm test'
  
#after_success: npm test
