version: '2'

services:

  habiticalite:
    build: .
    image: habiticalite
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/habiticalite

  mongo:
    image: mongo
    expose:
      - "27017"

  nginx:
    image: nginx:stable
    volumes:
     - ./etc/nginx:/etc/nginx
    volumes_from:
     - habiticalite:ro
    links:
     - habiticalite:habiticalite
    ports:
     - "443:443"
    # environment:
    #  - NGINX_HOST=habits.haxejs.com
    #  - NGINX_PORT=443
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ##in mysite.template, the env variable should be: listen ${NGINX_PORT};


